version: '3.4'

services: 

  frontend:
    image: store:latest
    environment: 
      - ProductEndpoint=http://backend:8080
    ports:
      - "9000:8080"
    depends_on: 
      - backend
  backend:
    image: products:latest
    ports: 
      - "9005:8080"